// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcP0WLTY3PxDbdSgq1CNUOBXapUSR5l7A',
    appId: '1:1017775297859:web:16a78a1afa1df96cbbcbf6',
    messagingSenderId: '1017775297859',
    projectId: 'notes-flutter-application',
    authDomain: 'notes-flutter-application.firebaseapp.com',
    storageBucket: 'notes-flutter-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-cGnSJagO-2G3HWuQJtaZYUf89S7PcI',
    appId: '1:1017775297859:android:5ca017652d1c6e95bbcbf6',
    messagingSenderId: '1017775297859',
    projectId: 'notes-flutter-application',
    storageBucket: 'notes-flutter-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNMhrvrsLO845qR_UNSY36GSIUGxC0LCg',
    appId: '1:1017775297859:ios:d3aa81d53e8ecbccbbcbf6',
    messagingSenderId: '1017775297859',
    projectId: 'notes-flutter-application',
    storageBucket: 'notes-flutter-application.appspot.com',
    iosClientId: '1017775297859-ii6a9oumrh5lucbvdb6i2ju2kdrfhkmb.apps.googleusercontent.com',
    iosBundleId: 'hillary.co.ke.mynotes',
  );
}
